<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QAAsk Spotify Design 07</name>
   <tag></tag>
   <elementGuidId>6bd8befe-dccb-418e-a34a-d9e5f735c018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='highlighted-articles']/div/div/div[2]/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.swiper-slide.swiper-slide-active > div.style-module--slide--CysvJ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e59a245-801a-4974-9ed5-6b6660a55257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-module--slide--CysvJ</value>
      <webElementGuid>966252ee-e9c2-4772-8c6d-20df7cda5615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Q+AAsk Spotify Design 07</value>
      <webElementGuid>c78e1bb6-84b1-4088-ad53-f5928a64cca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highlighted-articles&quot;)/div[@class=&quot;hidden-without-js sd-container style-module--heavy-rotation--22rkz  style-module--reveal--1AybC&quot;]/div[@class=&quot;sd-container-inner style-module--wrapper--2J0bj&quot;]/div[@class=&quot;style-module--carousel--lq44W&quot;]/div[@class=&quot;swiper-container swiper-container-fade swiper-container-initialized swiper-container-horizontal&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;style-module--slide--CysvJ&quot;]</value>
      <webElementGuid>c2572d78-420f-4aea-980c-de4ee6f851d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='highlighted-articles']/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>a8c96a04-d37a-4b42-acb4-2918077d5949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaboration Secrets: Design X Engineering'])[1]/following::div[2]</value>
      <webElementGuid>06490dea-82ba-4a64-8532-888da23683f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Behind The Scenes'])[1]/following::div[2]</value>
      <webElementGuid>9d4883e9-fd91-4ea6-acc6-18074667e13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/div/div/div[2]/div</value>
      <webElementGuid>6fec1961-b5d2-4cca-ba92-4ec0fe78f713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Q+AAsk Spotify Design 07' or . = 'Q+AAsk Spotify Design 07')]</value>
      <webElementGuid>920e4665-0608-4fcd-a4ee-c569774bb794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
