<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Listen</name>
   <tag></tag>
   <elementGuidId>858fa6d3-9ede-415b-a164-3e03dcb92cc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='sd-topbar']/div/div/nav/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ca47de3-8333-45df-b8d0-17d9790fa5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listen</value>
      <webElementGuid>4cd11cea-48b8-4257-b638-76f177f98886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd-topbar&quot;)/div[@class=&quot;sd-container-inner&quot;]/div[@class=&quot;style-module--inner--1qRHH&quot;]/nav[@class=&quot;style-module--desktop-nav--22t5t&quot;]/ul[@class=&quot;unstyled-list style-module--navigation--Xeg87&quot;]/li[2]/a[@class=&quot;t-ui-2 style-module--item--2doqO&quot;]/span[1]</value>
      <webElementGuid>ced5d5f0-5530-4b20-ad1e-f0ca5698f9f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='sd-topbar']/div/div/nav/ul/li[2]/a/span</value>
      <webElementGuid>7b304728-cffe-428e-a6e3-1a5f1c07afb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories'])[1]/following::span[1]</value>
      <webElementGuid>6e18a465-bc35-447f-8bb1-b8e48bc03c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::span[2]</value>
      <webElementGuid>d8e6ab74-1282-460a-9d51-e7325103858c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/preceding::span[1]</value>
      <webElementGuid>26b4f94b-13bd-41d1-ae1b-7102fca4a1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::span[2]</value>
      <webElementGuid>e1e961b2-70b2-45b0-a38c-31f447af2416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listen']/parent::*</value>
      <webElementGuid>51b9790c-2d24-4d6f-bcb8-0da5e35f85db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>f1e56674-1b0d-44c4-a78c-b4fa52516d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Listen' or . = 'Listen')]</value>
      <webElementGuid>c70f9264-c1f3-4ab8-867c-33806f6d28c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
