<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Stories</name>
   <tag></tag>
   <elementGuidId>4236dfdd-c4d1-4582-a0d9-40d83a91b16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='sd-topbar']/div/div/nav/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6f53793f-81f0-4701-9c39-0c894fdd18a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stories</value>
      <webElementGuid>f53cae96-8c42-43aa-836d-de7ed0efeee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sd-topbar&quot;)/div[@class=&quot;sd-container-inner&quot;]/div[@class=&quot;style-module--inner--1qRHH&quot;]/nav[@class=&quot;style-module--desktop-nav--22t5t&quot;]/ul[@class=&quot;unstyled-list style-module--navigation--Xeg87&quot;]/li[1]/a[@class=&quot;t-ui-2 style-module--item--2doqO&quot;]/span[1]</value>
      <webElementGuid>8c81aec6-1ffc-48f9-ae99-10c86a781bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='sd-topbar']/div/div/nav/ul/li/a/span</value>
      <webElementGuid>66762682-19f0-4ac0-805c-1921b203a613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::span[1]</value>
      <webElementGuid>a7100e22-dac7-4bb5-9664-e08be68e9e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Listen'])[1]/preceding::span[1]</value>
      <webElementGuid>5a15c46e-d132-451f-a0cc-ed2c9507b1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/preceding::span[2]</value>
      <webElementGuid>8b42e331-a63d-4c6e-87b0-33e6d33b3eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stories']/parent::*</value>
      <webElementGuid>339f7ec6-2dd3-4b5f-8367-2540eb4f5317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>dbac4947-ab88-4b0c-a2d7-9d556b367f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Stories' or . = 'Stories')]</value>
      <webElementGuid>60cdfcc0-89f6-45bb-bb02-0ef608585d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
