<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_sign_in</name>
   <tag></tag>
   <elementGuidId>7ba6b8dc-f8c4-484a-8305-072102601b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='sign_in']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;sign_in&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8790b83-f7c4-4f26-87f3-8b436a81cec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bcb320d5-2b17-4241-a548-27c68961dcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sign_in</value>
      <webElementGuid>50e7be9b-e48d-472b-9fa3-b7ccfa843af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>6cb223a5-c52a-4242-9a2d-af3ffe14a3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;completion_form&quot;)/div[6]/div[@class=&quot;center&quot;]/input[1]</value>
      <webElementGuid>03174f22-e04f-4fe2-8d58-c1a5b0b78c19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='sign_in']</value>
      <webElementGuid>4f01925d-180b-482f-b7b7-c73d6eff99bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='completion_form']/div[6]/div/input</value>
      <webElementGuid>ffabe881-a716-4fa0-9bb7-ac0a1d0823ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>1d4cae5c-7665-47fe-99b7-3779e0d46354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'sign_in']</value>
      <webElementGuid>852cf7f6-ee40-41b2-8bbf-884d3c15d3ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
