<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reference</name>
   <tag></tag>
   <elementGuidId>b7de749b-a9f3-42ad-89f2-a92acdbb5d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='sidebar-quicklinks']/nav/div/div/div/section/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfcb2303-0723-4242-bfc2-b19e77068b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>document-toc-link</value>
      <webElementGuid>11ecd506-b284-4b24-b417-4f820c4ace8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#reference</value>
      <webElementGuid>0688aa8f-e702-438c-8205-a3210501ee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reference</value>
      <webElementGuid>8968ab9e-404a-413e-9822-96d3cb78739f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-quicklinks&quot;)/nav[@class=&quot;sidebar-inner&quot;]/div[@class=&quot;sidebar-inner-nav&quot;]/div[@class=&quot;in-nav-toc&quot;]/div[@class=&quot;document-toc-container&quot;]/section[@class=&quot;document-toc&quot;]/ul[@class=&quot;document-toc-list&quot;]/li[@class=&quot;document-toc-item&quot;]/a[@class=&quot;document-toc-link&quot;]</value>
      <webElementGuid>64a9e451-70ce-4d6f-b68a-95f37d6dc389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='sidebar-quicklinks']/nav/div/div/div/section/ul/li[3]/a</value>
      <webElementGuid>27484694-14a9-4ead-b315-a22735c3ef1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Reference')])[2]</value>
      <webElementGuid>a0972c06-368f-43b4-8b6b-43e8c978978a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutorials'])[1]/following::a[1]</value>
      <webElementGuid>aab75877-1435-4d13-a922-49a244dd3b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key resources'])[1]/following::a[2]</value>
      <webElementGuid>be009cac-7ee9-4c3a-bae1-030bd166b9c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookbook'])[1]/preceding::a[1]</value>
      <webElementGuid>e7b7c572-cb50-487e-9dd7-c6d1219288ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools for CSS development'])[1]/preceding::a[2]</value>
      <webElementGuid>05ebc86c-5e06-430a-8895-b2ada9dd528f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reference']/parent::*</value>
      <webElementGuid>b7eac0e9-b496-4021-9be3-ca598f2e5c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#reference')]</value>
      <webElementGuid>4ecde6b2-9f0d-4a2a-a6cd-1e2bdeb814b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li[3]/a</value>
      <webElementGuid>ceb2a92a-4b62-4460-9163-6d7c9dbb0890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#reference' and (text() = 'Reference' or . = 'Reference')]</value>
      <webElementGuid>3dd9c8cd-4323-456f-8240-77f7c7d97341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
