<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Design</name>
   <tag></tag>
   <elementGuidId>5973e8f3-8163-4e3b-a473-bc32ee6653c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div/div/div/div[2]/div/div/nav/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.t-display-5.overlay-tune-in-module--link--13dRz.theme-design</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d30cbee4-6606-45cf-91ee-70bbe9e5afbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-display-5 overlay-tune-in-module--link--13dRz theme-design</value>
      <webElementGuid>8fd4473a-483f-435e-a54a-f2d57f9b40ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/stories/design</value>
      <webElementGuid>99fd67cd-dbf1-4f26-abe3-f5d0d22cfa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Design</value>
      <webElementGuid>39233c9a-1aa3-4115-9610-7370e0e096cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;style-module--app-shell--1Luo6&quot;]/div[@class=&quot;style-module--parent--2xIYu&quot;]/div[@class=&quot;style-module--hero--XGIUy&quot;]/div[@class=&quot;sd-container&quot;]/div[@class=&quot;sd-container-inner style-module--hero-inner--M1yz3 style-module--hero--1wZ_0&quot;]/div[1]/div[@class=&quot;style-module--fullHeight--1wZcB style-module--overlay--zVvPC  style-module--open--3akh1&quot;]/div[@class=&quot;style-module--inner--1_SKk&quot;]/div[@class=&quot;style-module--content--aiEki overlay-tune-in-module--overlay--2xh8s&quot;]/div[@class=&quot;overlay-tune-in-module--overlay-inner--3H4LN overlay-tune-in-module--open--1jbsL&quot;]/div[@class=&quot;sd-container&quot;]/nav[1]/ul[@class=&quot;unstyled-list overlay-tune-in-module--list--1rxll&quot;]/li[2]/a[@class=&quot;t-display-5 overlay-tune-in-module--link--13dRz theme-design&quot;]</value>
      <webElementGuid>52b8f9d2-c22c-4838-ba15-a8547adbc8eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div/div/div/div/div/div/div/div[2]/div/div/nav/ul/li[2]/a</value>
      <webElementGuid>8062d082-1e10-49d7-b098-484b2d1fa9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Design')]</value>
      <webElementGuid>7e8372f2-d4ac-4c6b-99af-23bc460ac7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Stories'])[1]/following::a[1]</value>
      <webElementGuid>a601d2cf-b4af-45f3-8302-17bf328733f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick a category'])[1]/following::a[2]</value>
      <webElementGuid>bbd5bef2-5078-4961-bf55-66c06a20880d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspiration'])[1]/preceding::a[1]</value>
      <webElementGuid>12d9089a-9af0-4108-8b57-80dba3110cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Noted'])[1]/preceding::a[2]</value>
      <webElementGuid>bef6a10c-d2d1-4f56-ad91-a0f7fa34e216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Design']/parent::*</value>
      <webElementGuid>ee5d3f42-1663-400c-b97f-7d0af33c4522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/stories/design')]</value>
      <webElementGuid>26ebcd8d-a564-48aa-bc03-4e4071bd6cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/nav/ul/li[2]/a</value>
      <webElementGuid>9dd3f031-0ea8-47cf-bd0b-6b8e67d469a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/stories/design' and (text() = 'Design' or . = 'Design')]</value>
      <webElementGuid>8bf59618-c2fa-47b9-84b3-2066d1f732c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
