<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Article</name>
   <tag></tag>
   <elementGuidId>4fe58a3b-a6d3-44e4-9d2b-3851446e3a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;View the content page [c]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ca-nstab-main']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>493037eb-8885-4fa8-b598-157b3839ba8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/JavaScript</value>
      <webElementGuid>4c51c56b-e7c2-4673-bf01-606ad78b01b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View the content page [c]</value>
      <webElementGuid>56a62dd4-0daf-422b-a7b5-7d69f48775c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>ebe06468-15e2-49c7-bcf1-103e29bbc4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Article</value>
      <webElementGuid>a71b721d-03db-46b3-bd82-3ceecd8ca911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ca-nstab-main&quot;)/a[1]</value>
      <webElementGuid>63d4d186-391b-44ea-a252-88053e84ca5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ca-nstab-main']/a</value>
      <webElementGuid>1f65de21-a7d8-43ae-9e0b-22a8b60c4541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page contents not supported in other languages.'])[1]/following::a[1]</value>
      <webElementGuid>657559b7-599e-492f-bc95-0204227db1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add languages'])[1]/following::a[1]</value>
      <webElementGuid>1083ab94-7fb4-4600-a2d7-86a72730190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talk'])[3]/preceding::a[1]</value>
      <webElementGuid>bdad2fde-2ed7-40d6-92d7-ae88df1f9a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wiki/JavaScript')]</value>
      <webElementGuid>ecc45352-2024-4343-a1c4-d14209bf509e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/nav/div/div/ul/li/a</value>
      <webElementGuid>ab36918e-204f-493c-a002-f9371bbd7678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/JavaScript' and @title = 'View the content page [c]' and (text() = 'Article' or . = 'Article')]</value>
      <webElementGuid>b1205f04-86df-44be-b909-9b6c4c703d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
