<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Wikipedia</name>
   <tag></tag>
   <elementGuidId>7bfdec3a-3354-4467-b7c1-3aa80e8393e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Welcome_to_Wikipedia']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Welcome_to_Wikipedia > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>003d0500-3dcc-4e12-9c2b-f063c5f2fdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wiki/Wikipedia</value>
      <webElementGuid>3813d85e-c692-4dee-8abd-5d7b71bea423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Wikipedia</value>
      <webElementGuid>954ec706-e437-4b14-916d-9412a06e95c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Welcome_to_Wikipedia&quot;)/a[1]</value>
      <webElementGuid>9d6fe711-5416-4304-8f82-846e5d0fee34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Welcome_to_Wikipedia']/a</value>
      <webElementGuid>fa5fe259-f710-4967-9487-6869dd49a8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Wikipedia')]</value>
      <webElementGuid>43222c89-fe78-475a-aecb-facf14b19b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='free'])[1]/preceding::a[1]</value>
      <webElementGuid>9ce0b2de-68ed-473e-8743-cb68554bf570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wikipedia']/parent::*</value>
      <webElementGuid>38464734-a908-43ba-bffd-3afb6c95df73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/wiki/Wikipedia')])[7]</value>
      <webElementGuid>aa10f655-c7f9-4d94-974b-48c6614c0448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span/a</value>
      <webElementGuid>f37e1a64-cca9-4e28-9efc-730cb8284088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wiki/Wikipedia' and (text() = 'Wikipedia' or . = 'Wikipedia')]</value>
      <webElementGuid>49aacc2e-33c9-44ea-977e-ce0ad3060701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
