<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3.2.1jQuery</name>
   <tag></tag>
   <elementGuidId>21966ef8-435b-44f6-bffa-dd67c757fba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toc-jQuery > a.vector-toc-link > div.vector-toc-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toc-jQuery']/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6238848a-ba8d-4537-8d3d-680a2b538993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vector-toc-text</value>
      <webElementGuid>93a4c9d8-2f61-4ecd-909b-6c4b055219e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				3.2.1jQuery</value>
      <webElementGuid>d1287c49-577a-4e4f-b446-2ba55f73356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toc-jQuery&quot;)/a[@class=&quot;vector-toc-link&quot;]/div[@class=&quot;vector-toc-text&quot;]</value>
      <webElementGuid>bc70c5c0-080b-4706-9528-0c873a4f2888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toc-jQuery']/a/div</value>
      <webElementGuid>3f2d3a84-26b9-4517-ac30-0ac805d0cccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jQuery']/parent::*</value>
      <webElementGuid>2383a150-8029-4e6c-bd5e-5915ec891b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/ul/li/a/div</value>
      <webElementGuid>aaf159e7-289b-498f-b8dd-31f5e79f195d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
				3.2.1jQuery' or . = '
				3.2.1jQuery')]</value>
      <webElementGuid>ff53d22e-da66-4155-a747-565fed430d9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
