<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign in_callout</name>
   <tag></tag>
   <elementGuidId>d4248ea4-da0c-4283-a4c5-bfb891e3eb66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='callout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;callout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2129ea19-a47b-41b9-b3c3-f12405fe6e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d6411c73-db6d-47d6-801b-3f469f8ea828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5bedc2ff-2684-44c8-8371-0eaaed16a8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>cb23e241-997d-4aa1-a513-95260e9d5f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>callout</value>
      <webElementGuid>97f2a4e0-cd62-43ce-b62f-963ec3fa86b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ogs.google.com/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=3c3dcea9c33016af&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Fwww.google.com&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=en</value>
      <webElementGuid>52a94f5d-139e-411c-925b-9647fe7b97e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_vd gb_9a gb_kd&quot;]/div[3]/iframe[1]</value>
      <webElementGuid>446d4ebe-d407-42d4-bc0a-38e21db84d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='callout']</value>
      <webElementGuid>e209a4da-d6b6-4a9a-bc2b-f06a0f4319af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[3]/iframe</value>
      <webElementGuid>7912fe7c-50e7-40da-aada-34e76fb4e439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fa8720d4-683d-41e7-86eb-5c21f4512a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'callout' and @src = 'https://ogs.google.com/widget/callout?prid=19037050&amp;pgid=19037049&amp;puid=3c3dcea9c33016af&amp;cce=1&amp;dc=1&amp;origin=https%3A%2F%2Fwww.google.com&amp;cn=callout&amp;pid=1&amp;spid=538&amp;hl=en']</value>
      <webElementGuid>aaa5e3e8-80d8-4e15-bd80-7a56bfe6452d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
