<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign in_lnXdpd</name>
   <tag></tag>
   <elementGuidId>10fb0b2b-1679-465c-a440-3f5a45ce5aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Google']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.lnXdpd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5bae58d-28cd-497f-b0a3-fd81431891cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnXdpd</value>
      <webElementGuid>b0a45d98-4491-4e12-9318-a224e0279fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Google</value>
      <webElementGuid>30a1de24-7d80-436b-a884-761c5b4c0d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>92</value>
      <webElementGuid>04ed86f0-71fc-4def-bcad-53bf952f7fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png</value>
      <webElementGuid>92b3fb9a-ae49-43b2-a4d2-5be6d2c531df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png 1x, /images/branding/googlelogo/2x/googlelogo_color_272x92dp.png 2x</value>
      <webElementGuid>ac5dd3c1-960d-4720-9375-10e192ca611d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>272</value>
      <webElementGuid>1c027287-8e61-4871-afc4-163d2d9a73d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e578e61c-1059-416e-a1e5-786510f7791b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frt</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>123125ca-0316-4601-bc26-b511420b1bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 LLD4me yr19Zb LS8OJ&quot;]/div[@class=&quot;k1zIA rSk4se&quot;]/img[@class=&quot;lnXdpd&quot;]</value>
      <webElementGuid>fb53fa34-b0c9-4a41-a80c-06a976227779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Google']</value>
      <webElementGuid>594a636d-3a1e-470b-8681-185c8d8c9270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fe73d46e-b236-4976-83e7-a52a3a9845fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Google' and @src = '/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png']</value>
      <webElementGuid>7b99efbc-4ca3-44c8-ac71-79f40c66b16f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
