<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Using PostCSS</name>
   <tag></tag>
   <elementGuidId>101c3728-4d7d-4b64-b568-dfb60fe12ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/main/section/div/div/div/ul/li[2]/h2/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c8751852-42e2-49c4-b422-4a90dcb46b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex text-sm leading-6 font-semibold pt-3 pb-2.5 border-b-2 -mb-px text-slate-900 border-transparent hover:border-slate-300 dark:text-slate-200 dark:hover:border-slate-700</value>
      <webElementGuid>54cea52d-cd9c-4fbb-8cd3-c80b385967a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/docs/installation/using-postcss</value>
      <webElementGuid>078a82cb-1d26-49b3-a55a-cc38dc302e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Using PostCSS</value>
      <webElementGuid>561bfe2c-9892-4bd1-a3f7-1a00ee1741f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;overflow-hidden&quot;]/div[@class=&quot;max-w-8xl mx-auto px-4 sm:px-6 md:px-8&quot;]/div[@class=&quot;lg:pl-[19.5rem]&quot;]/main[@class=&quot;max-w-3xl mx-auto relative z-20 pt-10 xl:max-w-none&quot;]/section[@class=&quot;mb-16 relative&quot;]/div[@class=&quot;relative z-10&quot;]/div[@class=&quot;flex overflow-auto mb-6 -mx-4 sm:-mx-6&quot;]/div[@class=&quot;flex-none min-w-full px-4 sm:px-6&quot;]/ul[@class=&quot;border-b border-slate-200 space-x-6 flex whitespace-nowrap dark:border-slate-200/5 mb-px&quot;]/li[2]/h2[1]/a[@class=&quot;flex text-sm leading-6 font-semibold pt-3 pb-2.5 border-b-2 -mb-px text-slate-900 border-transparent hover:border-slate-300 dark:text-slate-200 dark:hover:border-slate-700&quot;]</value>
      <webElementGuid>c781675b-117a-4032-95c7-8d030e167198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/main/section/div/div/div/ul/li[2]/h2/a</value>
      <webElementGuid>ada59a20-116b-4109-89aa-ba6de973b436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Using PostCSS')]</value>
      <webElementGuid>5e5b15ed-aacd-41a5-ad55-f30b7b015465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tailwind CLI'])[1]/following::a[1]</value>
      <webElementGuid>65f57653-c0c6-4d83-a542-2655171258de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation'])[4]/following::a[2]</value>
      <webElementGuid>34ba0460-cff0-4a18-b587-32025cec4dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Framework Guides'])[1]/preceding::a[1]</value>
      <webElementGuid>2f6b998d-d4b2-4650-9e90-d3cb74a431c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Play CDN'])[1]/preceding::a[2]</value>
      <webElementGuid>8065013f-702a-4b0a-a073-b0786ae76938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Using PostCSS']/parent::*</value>
      <webElementGuid>595574d9-2f67-45fd-ba73-976fc7e73220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/docs/installation/using-postcss')]</value>
      <webElementGuid>865b3cb2-c617-455a-9dac-155f7b607b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/h2/a</value>
      <webElementGuid>61ffd2ff-0c29-4507-a157-96c73f66d83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/docs/installation/using-postcss' and (text() = 'Using PostCSS' or . = 'Using PostCSS')]</value>
      <webElementGuid>f410e0f7-fae6-48f4-971f-9089f851aa24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
