<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get started</name>
   <tag></tag>
   <elementGuidId>75b6c494-15cc-4c46-8d85-277c64e8335c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>791d4bba-454f-4ef7-bca5-0d137a537a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-slate-900 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50 text-white font-semibold h-12 px-6 rounded-lg w-full flex items-center justify-center sm:w-auto dark:bg-sky-500 dark:highlight-white/20 dark:hover:bg-sky-400</value>
      <webElementGuid>78706547-42ff-48ed-ba56-add700f1aaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/docs/installation</value>
      <webElementGuid>0ff0b644-761d-49d8-8740-a31a1f56582d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>03552234-d5d9-4d5e-a3c7-48c106378aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;mb-20 overflow-hidden sm:mb-32 md:mb-40&quot;]/header[@class=&quot;relative&quot;]/div[@class=&quot;px-4 sm:px-6 md:px-8&quot;]/div[@class=&quot;relative max-w-5xl mx-auto pt-20 sm:pt-24 lg:pt-32&quot;]/div[@class=&quot;mt-6 sm:mt-10 flex justify-center space-x-6 text-sm&quot;]/a[@class=&quot;bg-slate-900 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 focus:ring-offset-slate-50 text-white font-semibold h-12 px-6 rounded-lg w-full flex items-center justify-center sm:w-auto dark:bg-sky-500 dark:highlight-white/20 dark:hover:bg-sky-400&quot;]</value>
      <webElementGuid>3bda5e9d-4929-4bc2-9098-9a06aa2890b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div/div[3]/div/a</value>
      <webElementGuid>dff6b0cc-46b1-49c2-9757-d99c1cd8035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get started')]</value>
      <webElementGuid>fe3d9535-3b74-4f73-a625-ba6436bd49d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rotate-90'])[1]/following::a[1]</value>
      <webElementGuid>cb593604-c08f-4282-b9ab-e8e4e3de6aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='text-center'])[1]/following::a[1]</value>
      <webElementGuid>8d84a430-219d-48c2-aeae-4ddb41cd2559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick search...'])[1]/preceding::a[1]</value>
      <webElementGuid>f05a3faf-2b66-4eef-9e6d-ddc271dde310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>655c927e-d1f5-4e08-8af6-a8ec24db2e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/docs/installation')])[2]</value>
      <webElementGuid>ca8ef12c-ef60-4473-88de-6da22f8f5b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>3006aa38-31aa-4ffb-a1e2-2b95a8855b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/docs/installation' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>d27a1bb1-5763-4ba4-8768-0639a82faa0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
